name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Specify your desired Node.js version

      - name: Install Dependencies
        run: npm install
        working-directory: ./src/agent-servicing-website/src  # Specify the correct path

      - name: Build
        run: npm run build
        working-directory: ./src/agent-servicing-website/src  # Specify the correct path

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/agent-servicing-website/src/build 
